import type { FilterFieldDef } from "@/lib/filters/types";

export const FILTER_FIELDS: FilterFieldDef[] = [
  // --- Project Information ---
  { key: "estimateNumber", label: "Project ID", section: "Project Information", kind: "text" },
  { key: "bidName", label: "Project Name", section: "Project Information", kind: "text" },
  { key: "address", label: "Address", section: "Project Information", kind: "text" },
  { key: "city", label: "City", section: "Project Information", kind: "text" },
  { key: "state", label: "State", section: "Project Information", kind: "text" },
  { key: "zip", label: "Zip", section: "Project Information", kind: "text" },
  { key: "contactName", label: "Contact Name", section: "Project Information", kind: "text" },
  { key: "contactEmail", label: "Contact Email", section: "Project Information", kind: "text" },
  { key: "contactPhone", label: "Contact Phone", section: "Project Information", kind: "text" },
  { key: "contactCell", label: "Contact Cell", section: "Project Information", kind: "text" },
  { key: "contactFax", label: "Contact Fax", section: "Project Information", kind: "text" },
  {
    key: "parentChild",
    label: "Parent/Child",
    section: "Project Information",
    kind: "select",
    options: [
      { value: "parents_only", label: "Parents Only" },
      { value: "children_only", label: "Children Only" },
      { value: "both", label: "Both" },
      { value: "exclude", label: "Exclude" },
    ],
  },

  // --- Project Data (FollowupCRM parity) ---
  {
    key: "salesStatus",
    label: "Status",
    section: "Project Data",
    kind: "select",
    placeholder: "Select sales status",
    options: [
      { value: "evaluate_whether_to_bid", label: "Evaluate whether to bid" },
      { value: "not_pursued", label: "Not pursued" },
      { value: "bid_in_process", label: "Bid in process" },
      { value: "no_bid", label: "No Bid" },
      { value: "prospective_future_bid", label: "Prospective Future bid" },
      { value: "post_bid", label: "Post Bid" },
      { value: "rebid_budget", label: "Rebid- budget" },
      { value: "long_shot", label: "Long Shot" },
      { value: "in_the_running_to_win", label: "In the Running to win" },
      { value: "lost", label: "Lost" },
      { value: "won", label: "Won" },
    ],
  },
  {
    key: "subBuildingType",
    label: "Sub Building Type",
    section: "Project Data",
    kind: "select",
    placeholder: "Select marketing status",
    options: [
      { value: "other", label: "Other" },
      { value: "parochial", label: "Parochial" },
      { value: "private_college", label: "Private - College" },
      { value: "public_college", label: "Public - College" },
      { value: "public_elementary_school", label: "Public - Elementary School" },
      { value: "public_high_school", label: "Public - High School" },
      { value: "public_middle_junior_high_school", label: "Public - Middle/Junior High School" },
    ],
  },
  { key: "preBidDate", label: "Pre Bid", section: "Project Data", kind: "dateRange" },
  { key: "bidDate", label: "Bid Date", section: "Project Data", kind: "dateRange" },
  {
    key: "source",
    label: "Source",
    section: "Project Data",
    kind: "select",
    placeholder: "Select lead from",
    options: [
      { value: "dodge_data_analytics", label: "Dodge Data & Analytics" },
      { value: "the_blue_book", label: "The Blue Book" },
      { value: "smartsheet", label: "Smartsheet" },
      { value: "smartbid", label: "SmartBid.com" },
      { value: "procore", label: "ProCore" },
      { value: "planhub", label: "PlanHub" },
      { value: "pipeline", label: "PipeLine" },
      { value: "pantera", label: "Pantera" },
      { value: "isqft", label: "iSqFt" },
      { value: "government_construction_bids", label: "Government Construction Bids" },
      { value: "email_invites_only", label: "Email Invites Only" },
      { value: "e_builder", label: "e-Builder" },
      { value: "bid_central_canadian_construction", label: "Bid Central - Canadian Construction" },
      { value: "construction_bid_source", label: "Construction Bid Source" },
      { value: "coconstruct", label: "CoConstruct" },
      { value: "cmd_group_construction_market", label: "CMD Group - Construction Market" },
      { value: "building_radar", label: "Building Radar" },
      { value: "buildingconnected", label: "BuildingConnected" },
      { value: "buildertrend", label: "Buildertrend" },
      { value: "box_net", label: "Box.net" },
      { value: "bonfire", label: "Bonfire" },
      { value: "bidtracer", label: "BidTracer" },
      { value: "bidclerk", label: "BidClerk" },
    ],
  },
  {
    key: "estimator",
    label: "Estimator",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select estimator",
  },
  {
    key: "bidClerk",
    label: "Bid Clerk",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select account manager",
  },
  {
    key: "constructionType",
    label: "Construction Type",
    section: "Project Data",
    kind: "select",
    placeholder: "Select product and services",
    options: [
      { value: "renovation", label: "Renovation" },
      { value: "new_construction", label: "New Construction" },
    ],
  },
  {
    key: "constructionSubtype",
    label: "Building Type",
    section: "Project Data",
    kind: "select",
    placeholder: "Select client profiles",
    options: [
      { value: "data_center", label: "Data Center" },
      { value: "commercial", label: "Commercial" },
      { value: "airport", label: "Airport" },
      { value: "wastewater", label: "Wastewater" },
      { value: "rec_community", label: "Rec/Community" },
      { value: "public", label: "Public" },
      { value: "prince_georges_county_cbb", label: "Prince Georges County - CBB" },
      { value: "power_plant_facilities", label: "Power Plant Facilities" },
      { value: "other", label: "Other" },
      { value: "museum", label: "Museum" },
      { value: "military", label: "Military" },
      { value: "metro_facilities_public_transportation", label: "Metro Facilities/Public Transportation" },
      { value: "industrial", label: "Industrial" },
      { value: "state_of_maryland", label: "State of Maryland" },
      { value: "medical", label: "Medical" },
      { value: "laboratories", label: "Laboratories" },
      { value: "housing", label: "Housing" },
      { value: "hotels", label: "Hotels" },
      { value: "hotel", label: "Hotel" },
      { value: "federal", label: "Federal" },
      { value: "educational", label: "Educational" },
    ],
  },
  {
    key: "tradeBidType",
    label: "Bid Type",
    section: "Project Data",
    kind: "select",
    placeholder: "Select contract types",
    options: [
      { value: "insulation_sub", label: "Insulation - Sub" },
      { value: "demolition_sub", label: "Demolition - Sub" },
      { value: "general_construction", label: "General Construction" },
      { value: "demolition_prime", label: "Demolition - Prime" },
      { value: "insulation_prime", label: "Insulation - Prime" },
      { value: "concrete", label: "Concrete" },
      { value: "masonry", label: "Masonry" },
      { value: "wastewater", label: "Wastewater" },
      { value: "pass_thru", label: "Pass-Thru" },
      { value: "other_services", label: "Other Services" },
    ],
  },
  {
    key: "companyName",
    label: "Office",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select offices",
    soloRow: true,
  },
  { key: "bidNumber", label: "Bid Number", section: "Project Data", kind: "text" },
  {
    key: "bidBondStatus",
    label: "Bid Bond Status",
    section: "Project Data",
    kind: "select",
    placeholder: "Select Bid Bond Status",
    options: [
      { value: "not_ordered", label: "Not Ordered - Estimator needs to do" },
      { value: "ordered_not_received", label: "Ordered - from Surety not received" },
      { value: "received", label: "Received" },
    ],
  },
  { key: "winningCompetitor", label: "Winning Competitor", section: "Project Data", kind: "text" },
  {
    key: "budgetBid",
    label: "Budget Bid",
    section: "Project Data",
    kind: "select",
    placeholder: "Select Budget",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" },
      { value: "unknown", label: "Unknown" },
    ],
  },
  { key: "mikeEstimateRef", label: "MIKE Est. #", section: "Project Data", kind: "text" },
  {
    key: "pla",
    label: "PLA",
    section: "Project Data",
    kind: "select",
    placeholder: "Select PLA",
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  {
    key: "takeOffPerson2",
    label: "Take Off Person 2",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select Take Off Person 2",
  },
  {
    key: "takeOffPerson3",
    label: "Take Off Person 3",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select Take Off Person 3",
  },
  { key: "websiteForBiddingDocs", label: "Website for bidding docs", section: "Project Data", kind: "text" },
  { key: "altWebLocation1", label: "Alternate Web Location Site 1", section: "Project Data", kind: "text" },
  { key: "altWebLocation2", label: "Alternate Web Location Site 2", section: "Project Data", kind: "text" },
  { key: "altWebLocation3", label: "Alternate Web Location Site 3", section: "Project Data", kind: "text" },
  { key: "wbdUsername", label: "WBD - Username", section: "Project Data", kind: "text" },
  { key: "wbdPassword", label: "WBD - Password", section: "Project Data", kind: "text" },
  {
    key: "wageRateCategory",
    label: "Wage Rate Category",
    section: "Project Data",
    kind: "select",
    placeholder: "Select Wage Rate",
    options: [
      { value: "wage_rate_pw_dba", label: "Wage Rate (PW/DBA)" },
      { value: "non_wage_scale", label: "Non-Wage Scale" },
    ],
  },
  {
    key: "ocipCcipStatus",
    label: "OCIP/CCIP",
    section: "Project Data",
    kind: "select",
    placeholder: "Select OCIP/CCIP",
    options: [
      { value: "not_applicable", label: "Not Applicable" },
      { value: "yes_gl_workmans_comp", label: "Yes - GL & Workman Comp" },
      { value: "yes_gl_only", label: "Yes - GL Only" },
    ],
  },
  { key: "grossSqFootage", label: "Gross Sq Footage", section: "Project Data", kind: "text" },
  { key: "projectNumberIfAwarded", label: "Project # (if awarded)", section: "Project Data", kind: "text" },
  {
    key: "usCitizenOnly",
    label: "US Citizen Only",
    section: "Project Data",
    kind: "select",
    placeholder: "Select US Citizen Only",
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  { key: "fringe", label: "Fringe", section: "Project Data", kind: "text" },
  { key: "costPerEstimate", label: "Cost per estimate", section: "Project Data", kind: "text" },
  { key: "bidBondAmountRequested", label: "Bid Bond Amount Requested", section: "Project Data", kind: "text" },
  { key: "wageRateAmount", label: "Wage Rate Amount", section: "Project Data", kind: "text" },
  {
    key: "takeOffPerson",
    label: "Take Off Person",
    section: "Project Data",
    kind: "select",
    dynamic: true,
    placeholder: "Select Take Off Person",
  },
  { key: "awl1Username", label: "AWL 1 - Username", section: "Project Data", kind: "text" },
  { key: "awl1Password", label: "AWL 1 - Password", section: "Project Data", kind: "text" },
  { key: "awl2Username", label: "AWL 2 - Username", section: "Project Data", kind: "text" },
  { key: "awl2Password", label: "AWL 2 - Password", section: "Project Data", kind: "text" },
  { key: "awl3Username", label: "AWL 3 - Username", section: "Project Data", kind: "text" },
  { key: "awl3Password", label: "AWL 3 - Password", section: "Project Data", kind: "text" },
  { key: "estimatorBidDate", label: "Estimator Bid Date", section: "Project Data", kind: "date" },
  {
    key: "rebid",
    label: "Rebid",
    section: "Project Data",
    kind: "select",
    placeholder: "Select Rebid",
    options: [
      { value: "true", label: "Yes" },
      { value: "false", label: "No" },
    ],
  },
  { key: "engineerProjectNumber", label: "Engineer Project #", section: "Project Data", kind: "text" },

  // --- Record Details ---
  { key: "baseBidAmount", label: "Base Bid", section: "Record Details", kind: "text" },
  { key: "contractAmount", label: "Contract Amount", section: "Record Details", kind: "text" },
  { key: "contractDate", label: "Contract Date", section: "Record Details", kind: "dateRange" },
  { key: "loginDate", label: "Login Date", section: "Record Details", kind: "dateRange" },
  { key: "marginPercent", label: "Gross Margin %", section: "Record Details", kind: "text" },
  { key: "timeEstimate", label: "Labor Hours", section: "Record Details", kind: "text" },
  { key: "deadDate", label: "Dead Date", section: "Record Details", kind: "dateRange" },

  // --- Companies & Contacts ---
  {
    key: "clientCompanyName",
    label: "Companies",
    section: "Companies & Contacts",
    kind: "select",
    dynamic: true,
    placeholder: "Select companies",
  },
  {
    key: "contactName",
    label: "Contacts",
    section: "Companies & Contacts",
    kind: "select",
    dynamic: true,
    placeholder: "Select contacts",
  },

  // --- Sales Activities (exact FollowupCRM order) ---
  { key: "followUpDate", label: "Follow Up", section: "Sales Activities", kind: "dateRange" },
  { key: "initialContact", label: "Initial Contact", section: "Sales Activities", kind: "dateRange" },
  { key: "siteVisit", label: "Site Visit", section: "Sales Activities", kind: "dateRange" },
  { key: "bidDrafted", label: "Bid Drafted", section: "Sales Activities", kind: "dateRange" },
  { key: "bidDelivered", label: "Bid Delivered", section: "Sales Activities", kind: "dateRange" },
  { key: "frontEndDocs", label: "Front End Docs", section: "Sales Activities", kind: "dateRange" },
  { key: "jobStartDate", label: "Job Start Date", section: "Sales Activities", kind: "dateRange" },
  { key: "jobEndDate", label: "Job End Date", section: "Sales Activities", kind: "dateRange" },
  { key: "technicalDate", label: "Technical", section: "Sales Activities", kind: "dateRange" },
  {
    key: "heatTracingSubPricing",
    label: "Heat tracing Sub pricing to be included",
    section: "Sales Activities",
    kind: "dateRange",
  },
  { key: "prequalificationPackage", label: "Prequalification Package", section: "Sales Activities", kind: "dateRange" },
  { key: "mandatoryPreBid", label: "Mandatory Pre-Bid", section: "Sales Activities", kind: "dateRange" },
  { key: "comments", label: "Comments", section: "Sales Activities", kind: "text", multiline: true },

  // --- Attachments ---
  {
    key: "hasAttachments",
    label: "Include only projects with documents",
    section: "Attachments",
    kind: "checkbox",
  },
];

export const BIDDING_SAVED_VIEWS_KEY = "bidding-saved-views";
